### ISSUE TITLE
Allow for error webhooks

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-anchor-server#118]
When things go wrong there needs to be an alerting mechanism. We should allow anchors to plug in a webhooks endpoint that we post to on errors or warnings

**Comment by debnil** [comment]
I have a good sense of how to do this now, but it doesn't make sense to implement until #115 is landed, since a good chunk of the error handling would be in the changed withdrawal logic.

**Comment by JakeUrban** [comment]
I like this feature request, I'll close here and add it to django-polaris.
