### ISSUE TITLE
Update the toml to use https for transfer_server

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-anchor-server#123]
http://stellar-anchor-server.herokuapp.com/.well-known/stellar.toml

shows transfer server and web auth endpoint using http urls, they should be https

**Comment by debnil** [comment]
This depends on whether or not the server is using http or https. Django defaults to using `http` and gives the deployment environment the choice of using SSL. Hardcoding those values as `https` will result in subsequent errors in later GET requests. Maybe we should turn on SSL for the heroku deployment?

**Comment by msfeldstein** [comment]
Just realized it works if i use https to get the toml.
