### ISSUE TITLE
how to get working on Ubuntu 18.04

### ISSUE THREAD

**Issue by tempofr** [stellar/stellar-anchor-server#128]
### On Ubuntu 18.04 server

- Created an envs directory to keep all environments inside projects directory .
- Installed python3.7 and pip .
- Then I took pull of project using git

### For stellar-anchor-server (Requires pipenv):
- Cloned the project in the ubuntu server inside the projects directory .
- In the stellar-anchor-server directory, I renamed env.example to .env .
- Setted up environment variables in .env file .
- Installed python dependencies by sudo apt-get install python3.7 python-dev python3.7-dev, which helped to successfully install all the packages from pipfile.lock which serves as requirements.txt in case of pipenv .
- Set up nginx (Requires some project config too) .
- Followed github steps for installing redis ,migrating and running the project with pipenv .

**Comment by JakeUrban** [comment]
Installation instructions has been added to the README and Sphinx documentation. Closing this now.
