### ISSUE TITLE
Use different accounts for asset issuer and anchor server

### ISSUE THREAD

**Issue by ronaldoy** [stellar/stellar-anchor-server#129]
The anchor server Stellar account is also the asset issuer. If the server is compromised, it is possible to issue as many tokens as wanted, killing the anchor business. 
With separate accounts, asset issuance can be controlled with multiple signatures and in another environment. 
It is closer to the recommended implementation (https://www.stellar.org/developers/guides/issuing-assets.html) and similar to how crypto exchanges deal with assets (hot/cold wallets).

**Comment by debnil** [comment]
Closed by #131
