### ISSUE TITLE
Send asset from issuer account to distribution account

### ISSUE THREAD

**Issue by debnil** [stellar/stellar-anchor-server#139]
Since we're separating the issuer and distribution account, we need to make an easy way to send amounts of the issued asset from the issuer to the distributor. A top up button in the admin panel may be a good approach for this.

**Comment by JakeUrban** [comment]
Managing issued assets is handled by @msfeldstein 's create-stellar-token npx tool. There are also plans to merge this tool into this project or django-polaris.
