### ISSUE TITLE
Proposal: make stellar-anchor-server a Django Package

### ISSUE THREAD

**Issue by accordeiro** [stellar/stellar-anchor-server#141]
### Intro

Our current reference implementation provides a good solution for people who want to:

- Have a quick glance at how specific parts of SEP-24 can be implemented
- Quickly bootstrap an anchor server and see SEPs 10 and 24 in action
- Have an initial codebase that they can fork and build upon to create their own transfer server

However, the way things are currently architected also brings up some challenges for anchors, such as:

1. Since the usage of the codebase is fork-based, it is hard to incorporate upstream updates once the downstream codebase has considerably diverged
2. It is hard to understand what the integration points are, i.e., the parts that the Anchors need to customize/modify in order to have a successfully functioning anchor

### Proposed Solution
In order to address these concerns, one possible solution is to make a [reusable Django Package](https://docs.djangoproject.com/en/2.2/intro/reusable-apps/) called `polaris` containing all the standard SEP 10 and 24 endpoints with the ability to override specific integration points – which would be the only parts that anchors would need to modify in order to make a fully functional transfer server.

With `polaris` in place, an anchor would simply need to create a Django project and add `”polaris”` to their list of `INSTALLED_APPS` on their `settings.py` in order to have a working transfer server. 

We could, of course, keep a reference implementation that illustrates how to use the `polaris` package in a real-life scenario, but forking said reference codebase would be entirely optional.

Incorporating upstream updates becomes as simple as updating any dependency on a Python project, and we can use semantic versioning to signal when it's safe to update, and when some breaking change is added.

#### Known Caveats

- Splitting the SEP 10 and 24 endpoints and models from the reference implementation would require us to maintain 2 codebases, instead of one
- This solution will still be Django-specific, so the anchor still wouldn't have the freedom to choose a different Python framework
- We currently rely on background tasks running on Celery, which might become a problem if we want to build an isolated Django app (that doesn't depend on Celery). This will require some rethinking of the async task strategy, but we could probably achieve what we need by creating long-running Django commands instead of Celery tasks.
- We'll need to keep up with Django updates, since we have no control of which Django version is being used by the anchors.

#### Transition Plan

This is an initial checklist for the transition to a [Django reusable app](https://docs.djangoproject.com/en/2.2/intro/reusable-apps/): 
- [ ] Fork this repo into a new one, called `polaris` 
- [ ] Merge all our Django apps (sep10auth, deposit, withdraw, etc) into a single app named `polaris`
- [ ] Map the functions that will become integration points and will need to be overridden, and define a strategy to easily make them override-able.
- [ ] Follow the [official packaging instructions](https://docs.djangoproject.com/en/2.2/intro/reusable-apps/#packaging-your-app)
- [ ] Create a documentation on how to use the package
- [ ] Publish the Python package
- [ ] Update `stellar-anchor-server` to become a very stripped down reference implementation that simply imports `polaris`, overrides some integration points, and provides a `docker-compose` file that runs all the necessary background Django commands (former Celery tasks)

### Open questions
1. Should we aim at building something more framework-agnostic?
2. This will admittedly require a lot of work – should we pursue something simpler, like providing better documentation on the integration points?

---
Would love to get your thoughts on this @tomerweller @msfeldstein  @tomquisel @vitchor @debnil

**Comment by debnil** [comment]
I'm a fan of this proposal. I think it preserves the original goal of the reference server - "give anchors reference code for implementing their own SEP 10 and 24 server" - while adapting to the reality that anchors are using this code directly. This provides a modular approach to updates and helps resolve confusion over the integration points. I think @accordeiro outlined the benefits really well, so not reinventing the wheel.

I don't think any of these caveats are too large - answering them in turn. Given the above benefits, I think any of the below has to be a substantial drag on development to justify not picking.
1. Maintaining 2 codebases: maybe I'm misunderstanding, but the `stellar-anchor-server` codebase seems like it would just be a thin wrapper around polaris. Seems like very little extra maintenance.
2. This is the biggest caveat to me, but still not significant enough to outweigh the proposal's benefits. Answering it more fully in the open question.
3. Background tasks on Celery - having refactored the withdrawal task to a long-running Django command, it really wasn't difficult implementation wise (PR linked [here](https://github.com/stellar/stellar-anchor-server/pull/115)). Refactoring unit tests may be a bit painful, but it definitely seems worth this effort. Deployment was a bit annoying - we'll have to run a couple more Heroku dynos and add a couple containers to Docker - but I don't think it's close to a dealbreaker.
4. If a Django update is big enough to trigger concern, we'd probably have to update the reference implementation.

Open questions
1. This is a great question, and I think it should guide this decision. This seems to more feedback from anchors' dev teams, regarding whether or not they're comfortable using Django. To be fair, that is a bit of a slippery slope, and I'm not sure what something "framework-agnostic" looks like. If we create something more framework agnostic, then does it make sense to we implement in a different language that more anchors use (e.g., Java)? 
2. If this would be valuable to anchors (which it seems like it would), the work seems worthwhile. The majority of work seems to be around defining the integration points, since every other step is pretty well-documented. However, making anchors more productive still requires good definition of those integration points and, on top of that, specific help with per-anchor implementation. Even if that's not our job per se, it seems like it'll be inevitable absent making it drop-dead easy to integrate. Making integration as frictionless as possible definitely seems worth it.

A note - taking this step seems like a large philosophical shift - we've made it implicitly, but it seems worth discussing explicitly. It means that we accept that this is no longer a reference, but a core piece of the anchor codebase. If we proceed along this path, we should think about the security implications and make sure we take necessary precautions.

**Comment by vitchor** [comment]
I also think this proposal makes a lot of sense. With both repos we can have an easy way for Anchors to get started and a simpler code updating process for them in the future.

Regarding choosing a language/framework: besides being able to reutilize the current codebase, the Python/Django option also seems to have a pretty good community support.

Django is, by far, the most active Python framework on StackOverflow:
<img width="605" alt="Screen Shot 2019-10-18 at 2 12 47 PM" src="https://user-images.githubusercontent.com/630755/67114051-61926400-f1b1-11e9-85bd-9235d885bbd6.png">

And Python seems to have a good trend as well:
<img width="608" alt="Screen Shot 2019-10-18 at 2 14 06 PM" src="https://user-images.githubusercontent.com/630755/67114355-19c00c80-f1b2-11e9-9d5e-51c2cef4b1e8.png">

I do wonder if we'd have features/functionalities restrictions in the future if we decide to move forward with the Django App route. @accordeiro, can you think of some type of functionality that we wouldn't be able to implement in this format?

**Comment by accordeiro** [comment]
Thanks for your input, guys! Following up on a few items:

> <@debnil> This is a great question, and I think it should guide this decision. This seems to more feedback from anchors' dev teams, regarding whether or not they're comfortable using Django. To be fair, that is a bit of a slippery slope, and I'm not sure what something "framework-agnostic" looks like. If we create something more framework agnostic, then does it make sense to we implement in a different language that more anchors use (e.g., Java)?

That's a good point. I feel like we wouldn't be able to select anything that'd be too framework-agnostic, though, since SEP24 & 10 are basically a collection of HTTP(S) endpoints, so we'd end up in the same situation, but probably switching from something Django-specific to Flask- or Tornado-specific. Does that make sense? Plus, from the stats that @vitchor posted, Django seems like a solid choice.

Changing languages would mean not reusing what we've already built and validated, which I'm not sure is the best path forward.

> <@vitchor> @accordeiro, can you think of some type of functionality that we wouldn't be able to implement in this format?

Apart from things that heavily rely on external infrastructure / tools (like the Celery bit I've mentioned), it seems like everything else that we'd normally achieve on a normal Django application should be possible. 

As @debnil mentioned, if we want to move forward with this approach, one important part (if not the most important one) is to decide on the interface anchors would use to integrate their banking rails / KYC, as well as to customize some parts to suit their needs. 

It seems like using [Django Signals](https://docs.djangoproject.com/en/2.2/topics/signals/) would be a good approach – we'd dispatch signals for things like Deposit / Withdrawal requests, detecting a payment on the Stellar network, etc., and would provide a good documentation on how to listen to those signals and add custom steps. 

For the interactive parts, we could use Django templates (which could be [easily overridden](https://docs.djangoproject.com/en/2.2/howto/overriding-templates/)), although we'd probably need to override the Django views themselves for things like the KYC submission since the form fields themselves would probably vary considerably. One idea is to add a setting to `settings.py` which points to the KYC handling view – but maybe there's a more clever approach for that?

**Comment by msfeldstein** [comment]
> we wouldn't be able to select anything that'd be too framework-agnostic, though, since SEP24 & 10 are basically a collection of HTTP(S) endpoints

While its impossible to be framework agnostic, i think there is value to being framework-lighter.  Flask as a framework is basically "a collection of http(s) endpoints" which to me makes it a lot clearer, while django is very heavy and i had to learn django before i could see the SEP work.  As a reference, it would be easier for people to see whats going on at a glance, and for production, it would be easier for people to build whatever frameworks on top of it that they wanted to use. Django comes with a lot of boilerplate, redirection, and opinions.  For example, if someone wanted to use react for their KYC, it seems a lot easier to host a standalone react app on top of flask than django.

**Comment by accordeiro** [comment]
That's a great point @msfeldstein. I definitely agree that one needs some Django context (and understand some specific and sometimes misleading terms like `views`) before they can actually know their way around the codebase and see where the SEP implementations are.

That said, this proposal is to actually abstract everything away, so you basically have to import a library in Django and override some specific integration points as needed, enabling people to easily merge upstream updates without worrying about merge conflicts, etc.

If we were to move to something like Flask, is your idea that we keep recommending Anchors to actually fork the codebase? Or would we try the same library / package approach, but in a different framework? Flask does seem to have a concept of [modular applications with Blueprints](https://flask.palletsprojects.com/en/1.1.x/blueprints/), but I've never used it. Also, we'd probably need to be opinionated about database connection (maybe using something like SQLAlchemy to enable usage of different engines), and how to run background jobs. Maybe we should investigate this path a bit further to have a tradeoff comparison?

**Comment by msfeldstein** [comment]
> this proposal is to actually abstract everything away, so you basically have to import a library in Django 

This sounds like we're giving up on the idea of it being a reference to anyone who wants to implement it themselves, which to me was the most important thing.  I found most of the value being an example of how to use the stellar SDK to implement most of these endpoints.  The further we move from that the less value we're providing anyone who doesn't use python.  A flask implmentation would be useful as a reference to someone writing in any language.

I also don't see any reason people couldn't fork this codebase if it used flask, i think it would actually be even easier to create the API surface needed for them to extend it to use their own connectors.  The Database abstraction is definitely a value that django adds, but unless most anchors are starting from scratch, they probably have their own db they want to continue using, which negates any benefit of django's ORM

**Comment by accordeiro** [comment]
> This sounds like we're giving up on the idea of it being a reference to anyone who wants to implement it themselves, which to me was the most important thing.

The fundamental change proposed here is _how_ you use the reference implementation, but it doesn't remove your ability to take a look at the source code for reference and/or fork it to build your own custom implementation. The Django package would look pretty similar to our current codebase, with the additional feature that you can actually import it and extend it without actually touching the underlying implementation if you don't want to – except for the mandatory integration points. Does that make sense?

> A flask implmentation would be useful as a reference to someone writing in any language.

I agree with you on this. Flask does require less boilerplate and would be easier to grasp for anyone who wants to use this codebase as a reference.

> I also don't see any reason people couldn't fork this codebase if it used flask, i think it would actually be even easier to create the API surface needed for them to extend it to use their own connectors.

Yes, people would definitely be able to fork this codebase if it used Flask or any other framework. My only concern is that any `fork`-based approach makes it harder for people to incorporate upstream improvements / changes, which is one of the things this proposal aims to fix.

---

I feel like it all boils down to what we want the goal of this project to be moving forward. It could either become:

**a)** A codebase that anchors fork and use to build their own transfer server, or that they look at for inspiration when creating their own independent implementation, either in Python or another language.

or

**b)** A library that makes it very easy for Anchors to integrate with Stellar and keep up with the SEP-10, 24 & friends updates, while minimizing the code surface that they need to touch / update. Also worth mentioning that this option still allows people to look at the implementation and use it as a reference.

My general sense is that we were originally aiming towards `(a)`, but I feel like `(b)` is also valuable to speed up Anchor integration and incorporation of new SEP changes. Note that `b` doesn't necessarily have to be in Django, we could also provide that as a Flask library if we think that adds more value – or maybe even have different implementations in different languages / frameworks as our implementations become more stable?

**Comment by msfeldstein** [comment]
> Yes, people would definitely be able to fork this codebase if it used Flask or any other framework. My only concern is that any fork-based approach makes it harder for people to incorporate upstream improvements / changes, which is one of the things this proposal aims to fix.

Sorry fork was a poor choice of words, i just meant utilize. 
B is definitely important if we want people to use this code.

**Comment by ronaldoy** [comment]
Adding some anchor perspective:

1. The current Django implementation is extremely useful for anchors starting from scratch. If this is the way to go, it would be nice to have clear points on where to add KYC and bank integration and maybe an environment flag that when set moves /confirm_deposit from open to everyone to an option in the admin menu. 
For the documentation, a more detailed guide on production setup (we may help with this).

2. Flask version can be useful for larger anchors to just add SEP24 to their current implementations. If it is just as a reference, the current code seems reasonably easy to read. Although we had some experience with Python for data science and with Rails, we never used Django before and the learning curve wasn’t bad.

**Comment by ire-and-curses** [comment]
This might be worth a post to the dev mailing list to get more feedback.

**Comment by debnil** [comment]
The above are all great points. One thing I'll add - I don't see how building a Django plugin suddenly means that the codebase isn't useful as a reference. People can still look at the `polaris` repo and figure out what the logic behind an endpoint is. 

A large motivating factor in the initial choice of Django was the built-in admin panel, to make it easier for anchors to execute CRUD operations. How is Flask's support for this?

**Comment by msfeldstein** [comment]
1) It's still just as good of a reference, i don't think Django app vs Django plugin makes much of a difference for the referenceability

2) I think we've found that the django admin panel wasn't actually that useful at the end of the day and anchors would need to write them from scratch anyways, right?  I don't know that i would consider the django admin panel a benefit at this point.

**Comment by JakeUrban** [comment]
This was implemented! Closing now.
