### ISSUE TITLE
Redirect to receipt page instead of rendering

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-anchor-server#146]
When you submit the form from `/interactive_deposit` it succeeds and renders the `more_info.html` template, but the url is still `/interactive_deposit`.  This makes it so you can't refresh the page without trying to re-submit the form and it errors out.  Instead, we should submit the form, then redirect to the more info url since we're done with `interactive_deposit`

https://github.com/stellar/stellar-anchor-server/blob/master/src/deposit/views.py#L197
probably just need to replace render with redirect

**Comment by JakeUrban** [comment]
Closing and moving this to django-polaris

**Comment by JakeUrban** [comment]
https://github.com/stellar/django-polaris/issues/19
