### ISSUE TITLE
[SEP 6] Implement the /withdraw endpoint

### ISSUE THREAD

**Issue by accordeiro** [stellar/stellar-anchor-server#15]
We should implement the `/withdraw` workflow, according to the SEP 6 spec.
As we're favoring the interactive KYC flow in most cases, here's a proposed task list to accomplish the withdrawal flow:

1. (#91) Create a `/withdraw` endpoint that, once hit with valid query parameters, creates a transaction ID and returns (with a 403 status) a popup url and the transaction's ID. [Closed by #90]
2. (#92) Create a simple UI for the popup, which gathers the required withdrawal info and updates the corresponding transaction on the backend, thus initiating the withdrawal. [Closed by #90]
3. (#93) Create an async task that, once a withdrawal has been initiated, watches for a corresponding Stellar transaction. This transaction has a memo with the unique transaction ID provided above. Once that Stellar transaction is recorded, the transaction status needs to be changed to completed. [Addressed by #98]
4. Integrate the withdraw flow with sep6-demo-client and polish any rough edges.

**Comment by debnil** [comment]
Closed by the referenced PRs, works smoothly with the demo client.
