### ISSUE TITLE
The master branch failed to pass the tests.

### ISSUE THREAD

**Issue by overcat** [stellar/stellar-anchor-server#155]
I believe it's related to the test network reset a few days ago, maybe we should follow [testnet best practices](https://www.stellar.org/developers/guides/concepts/test-net.html#best-practices-for-using-testnet).

**Comment by overcat** [comment]
I activated these accounts with firendbot, it is ready for testing now.

**Comment by JakeUrban** [comment]
Thanks @overcat , closing now
