### ISSUE TITLE
documents?

### ISSUE THREAD

**Issue by ehsanhajian** [stellar/stellar-anchor-server#25]
I've installed stellar-anchor-server. how can I see the app? what's the django credentials? any documents?

**Comment by accordeiro** [comment]
Hi @ehsanhajian, this project is still a work in progress, created based on [Stellar's SEP6 specs](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md).

You can check the [`README.md`](/README.md) for setup instructions, or check out the tests to see what endpoints are available and what they do, but we're really early stage. 

The roadmap for the MVP implementation is defined in the [milestones section](https://github.com/stellar/stellar-anchor-server/milestones).

Hope that helps, and please let me know if you have any further questions :)
