### ISSUE TITLE
Fee fields for asset shouldn't be required

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-anchor-server#76]
When adding an asset `Deposit fee fixed` / `Deposit fee percent` / `Deposit min amount` / `Deposit max amount` are all required fields, but they are optional in the sep6 /info endpoint.  We should make them optional here as well (or just remove them since they're far less relevent in the interactive flow)

**Comment by debnil** [comment]
This should be closed by #78 - setting `blank=True` for those fields means that the field won't be required.
