### ISSUE TITLE
Issue assets on testnet

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-anchor-server#86]
Currently we create an asset in the admin panel, but those assets don't exist in the testnet, and the client has no way to get some to withdraw.  We should automatically issue a whole bunch and create a friendbot like faucet in the admin panel to request some.

Here is a JS Demo i use to issue assets, the transactions should be portable: https://github.com/msfeldstein/create-stellar-token/blob/master/index.js

**Comment by JakeUrban** [comment]
Closing because @msfeldstein created the https://github.com/msfeldstein/create-stellar-token project
