### ISSUE TITLE
Ensure we address all anchor pain points

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-anchor-server#95]
We repeatedly run into the same issues for all the anchors involved, so I want to make sure our reference server has a very clear answer to all of the issues people have, ideally we just send a github link to the lines that do what they need.  This issue collects all those pain points as comments

**Comment by msfeldstein** [comment]
"How do i communicate back to the wallet after i finished my KYC webapp"

**Comment by msfeldstein** [comment]
"How do i listen for incoming payments for withdrawal"

**Comment by msfeldstein** [comment]
"How do i set up a staging server that doesn't use live data"

**Comment by accordeiro** [comment]
Maybe we can create a `FAQ.md` we can point to, which references the code parts that answer each of these questions?

**Comment by JakeUrban** [comment]
Closing since we're building our roadmap partially by collecting anchor feedback
